import { Project, NavLink, Service, SocialLink } from './types'

export const projects: Project[] = [
  {
    id: 1,
    title: 'Château de Vaux',
    category: 'Cérémonie',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=1920&q=80',
    description: 'Un mariage d\'exception dans les jardins du Château de Vaux-le-Vicomte. La lumière dorée de l\'été magnifie chaque instant de cette journée hors du temps.',
    client: 'Camille & Alexandre',
    year: 2024,
    tags: ['Château', 'Cérémonie', 'Été'],
  },
  {
    id: 2,
    title: 'Villa Méditerranée',
    category: 'Reportage',
    image: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=1920&q=80',
    description: 'Reportage complet d\'un mariage en bord de mer sur la Côte d\'Azur. Lumières chaudes du coucher de soleil, fleurs blanches et emotion pure.',
    client: 'Elise & Thomas',
    year: 2024,
    tags: ['Côte d\'Azur', 'Mer', 'Sunset'],
  },
  {
    id: 3,
    title: 'Paris Intime',
    category: 'Portraits',
    image: 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1920&q=80',
    description: 'Séance portraits au cœur de Paris — jardins du Palais Royal, berges de la Seine, ruelles du Marais. Un ballet silencieux entre deux âmes.',
    client: 'Marie & Julien',
    year: 2024,
    tags: ['Paris', 'Portraits', 'Urbain'],
  },
  {
    id: 4,
    title: 'Mas Provençal',
    category: 'Détails',
    image: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1920&q=80',
    description: 'Chaque détail raconte une histoire. La bague, le bouquet de pivoines, la robe sur le lit de lavande... Un mariage provençal plein de douceur.',
    client: 'Léa & Pierre',
    year: 2024,
    tags: ['Provence', 'Détails', 'Fleurs'],
  },
  {
    id: 5,
    title: 'Toscane Éternelle',
    category: 'Destination',
    image: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?w=1920&q=80',
    description: 'Destination wedding en Toscane — cyprès, vignobles dorés, villa du XVIe siècle. Un mariage qui ressemble à un tableau de la Renaissance.',
    client: 'Sarah & Maxime',
    year: 2023,
    tags: ['Toscane', 'Destination', 'Vignoble'],
  },
  {
    id: 6,
    title: 'Domaine Alsacien',
    category: 'Réception',
    image: 'https://images.unsplash.com/photo-1583939411023-14783179e581?w=1920&q=80',
    description: 'La joie d\'une réception alsacienne au cœur des vignes. Tables fleuries, chandelles et convives enchantés — la vie dans toute sa beauté.',
    client: 'Claire & Hugo',
    year: 2023,
    tags: ['Alsace', 'Réception', 'Vignes'],
  },
  {
    id: 7,
    title: 'Bretagne Sauvage',
    category: 'Reportage',
    image: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=1920&q=80',
    description: 'Mariage face à l\'Atlantique — falaises brettonnes, embruns, regard amoureux. La nature comme décor grandiose d\'une union authentique.',
    client: 'Manon & Romain',
    year: 2023,
    tags: ['Bretagne', 'Ocean', 'Nature'],
  },
  {
    id: 8,
    title: 'Bal de Minuit',
    category: 'Soirée',
    image: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1920&q=80',
    description: 'La nuit qui libère — piste de danse, lumières tamisées, rires et larmes mêlés. Ces instants volés entre minuit et l\'aube sont mes préférés.',
    client: 'Anaïs & Victor',
    year: 2024,
    tags: ['Soirée', 'Danse', 'Nuit'],
  },
  {
    id: 9,
    title: 'Jardin Secret',
    category: 'Cérémonie',
    image: 'https://images.unsplash.com/photo-1525772764200-be829a350797?w=1920&q=80',
    description: 'Une cérémonie laïque dans un jardin privé, entourés de leurs proches. Les bouquets de pivoines roses et les sourires des enfants ont tout illuminé.',
    client: 'Inès & Baptiste',
    year: 2023,
    tags: ['Jardin', 'Cérémonie Laïque', 'Fleurs'],
  },
  {
    id: 10,
    title: 'Alpes Féeriques',
    category: 'Destination',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1920&q=80',
    description: 'Mariage en altitude dans les Alpes françaises. Neige immaculée, chalet en bois, fourrures douces et panorama à couper le souffle.',
    client: 'Charlotte & Louis',
    year: 2024,
    tags: ['Alpes', 'Montagne', 'Hiver'],
  },
  {
    id: 11,
    title: 'Orangerie de Paris',
    category: 'Portraits',
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1920&q=80',
    description: 'Séance en lumière naturelle dans une orangerie parisienne du XIXe siècle. La lumière filtrée à travers les verrières crée une atmosphère onirique.',
    client: 'Juliette & Édouard',
    year: 2023,
    tags: ['Paris', 'Orangerie', 'Lumière naturelle'],
  },
  {
    id: 12,
    title: 'Riviera Glamour',
    category: 'Destination',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1920&q=80',
    description: 'Destination wedding à Monaco — coupé décapotable, robes haute couture, yacht au crépuscule. L\'image parfaite du glamour méditerranéen.',
    client: 'Sophia & Antoine',
    year: 2024,
    tags: ['Monaco', 'Luxe', 'Yacht'],
  },
]

export const navLinks: NavLink[] = [
  { label: 'Portfolio', href: '#portfolio' },
  { label: 'Histoire', href: '#about' },
  { label: 'Contact', href: '#contact' },
]

export const services: Service[] = [
  { icon: 'Camera',  label: 'Reportage complet',  description: 'De la préparation à la soirée' },
  { icon: 'Heart',   label: 'Séance engagement',  description: 'Portraits avant le grand jour' },
  { icon: 'Image',   label: 'Album haut de gamme', description: 'Tirage fine art, reliure cuir' },
  { icon: 'Plane',   label: 'Destination',         description: 'France et international' },
  { icon: 'Sparkles', label: 'Post-production',    description: 'Retouche et étalonnage luxe' },
]

export const socialLinks: SocialLink[] = [
  { platform: 'Instagram', url: 'https://instagram.com', icon: 'Instagram' },
  { platform: 'Pinterest', url: 'https://pinterest.com', icon: 'Pin' },
  { platform: 'Facebook',  url: 'https://facebook.com',  icon: 'Facebook' },
  { platform: 'YouTube',   url: 'https://youtube.com',   icon: 'Youtube' },
]

export const companyInfo = {
  name: 'Sophie Laroche',
  email: 'bonjour@sophielaroche.fr',
  phone: '+33 (0)6 12 34 56 78',
  address: 'Paris, France — disponible partout',
  tagline: 'L\'art de capturer l\'amour',
}
