import { Project, NavLink, Service, SocialLink } from './types'

export const projects: Project[] = [
  {
    id: 1,
    title: 'Luxury Campaign',
    category: 'Commercial',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1920&q=80',
    description: 'Premium brand campaign for a luxury fashion house, blending cinematic storytelling with high-end aesthetics.',
    client: 'Maison Élégance',
    year: 2024,
    tags: ['Fashion', 'Commercial', '4K'],
  },
  {
    id: 2,
    title: 'Urban Rhythms',
    category: 'Music Video',
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1920&q=80',
    description: 'Dynamic music video capturing the pulse of city life through innovative visual techniques.',
    client: 'Nova Records',
    year: 2024,
    tags: ['Music', 'Urban', 'Creative'],
  },
  {
    id: 3,
    title: 'Horizon Motors',
    category: 'Automotive',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1920&q=80',
    description: 'High-octane automotive commercial showcasing the power and elegance of luxury vehicles.',
    client: 'Horizon Motors',
    year: 2024,
    tags: ['Automotive', 'Luxury', 'Commercial'],
  },
  {
    id: 4,
    title: 'Ethereal Beauty',
    category: 'Beauty',
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?w=1920&q=80',
    description: 'Intimate beauty campaign exploring light, texture, and the art of self-expression.',
    client: 'Lumière Cosmetics',
    year: 2023,
    tags: ['Beauty', 'Editorial', 'Cinematic'],
  },
  {
    id: 5,
    title: 'Wilderness',
    category: 'Documentary',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1920&q=80',
    description: 'Award-winning documentary capturing the raw beauty of untouched landscapes.',
    client: 'National Geographic',
    year: 2023,
    tags: ['Documentary', 'Nature', 'Aerial'],
  },
  {
    id: 6,
    title: 'Tech Summit 2024',
    category: 'Corporate',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1920&q=80',
    description: 'Comprehensive event coverage for the worlds largest technology conference.',
    client: 'TechVentures Inc.',
    year: 2024,
    tags: ['Corporate', 'Event', 'Live'],
  },
  {
    id: 7,
    title: 'Artisan Stories',
    category: 'Brand Film',
    image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?w=1920&q=80',
    description: 'Documentary-style brand film celebrating traditional craftsmanship and heritage.',
    client: 'Heritage Collective',
    year: 2023,
    tags: ['Documentary', 'Brand', 'Storytelling'],
  },
  {
    id: 8,
    title: 'Midnight Noir',
    category: 'Short Film',
    image: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1920&q=80',
    description: 'Atmospheric short film exploring themes of mystery and urban solitude.',
    client: 'Independent',
    year: 2023,
    tags: ['Narrative', 'Cinematic', 'Noir'],
  },
  {
    id: 9,
    title: 'Culinary Arts',
    category: 'Food & Beverage',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1920&q=80',
    description: 'Sensory-rich food cinematography for Michelin-starred restaurants.',
    client: 'Gastronomique Magazine',
    year: 2024,
    tags: ['Food', 'Lifestyle', 'Commercial'],
  },
  {
    id: 10,
    title: 'Velocity',
    category: 'Sports',
    image: 'https://images.unsplash.com/photo-1461896836934- voices-a4d7ed?w=1920&q=80',
    description: 'High-speed sports documentary capturing athletes at their peak performance.',
    client: 'Sports Illustrated',
    year: 2024,
    tags: ['Sports', 'Documentary', 'Action'],
  },
  {
    id: 11,
    title: 'Neon Dreams',
    category: 'Music Video',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1920&q=80',
    description: 'Visually stunning music video with cutting-edge visual effects and neon aesthetics.',
    client: 'Electric Records',
    year: 2024,
    tags: ['Music', 'VFX', 'Creative'],
  },
  {
    id: 12,
    title: 'Sustainable Future',
    category: 'Corporate',
    image: 'https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1920&q=80',
    description: 'Environmental awareness campaign highlighting sustainable business practices.',
    client: 'GreenTech Solutions',
    year: 2023,
    tags: ['Corporate', 'Environmental', 'Documentary'],
  },
]

export const navLinks: NavLink[] = [
  { label: 'Work', href: '#work' },
  { label: 'About', href: '#about' },
  { label: 'Contact', href: '#contact' },
]

export const services: Service[] = [
  { icon: 'Camera', label: 'Photography', description: 'Editorial and commercial photography' },
  { icon: 'Video', label: 'Videography', description: 'Cinematic video production' },
  { icon: 'Film', label: 'Post-Production', description: 'Editing, VFX, and color grading' },
  { icon: 'Palette', label: 'Color Grading', description: 'Professional color correction' },
  { icon: 'Plane', label: 'Aerial Footage', description: 'Drone and aerial cinematography' },
]

export const socialLinks: SocialLink[] = [
  { platform: 'Instagram', url: 'https://instagram.com', icon: 'Instagram' },
  { platform: 'LinkedIn', url: 'https://linkedin.com', icon: 'Linkedin' },
  { platform: 'Vimeo', url: 'https://vimeo.com', icon: 'Play' },
  { platform: 'YouTube', url: 'https://youtube.com', icon: 'Youtube' },
]

export const companyInfo = {
  name: 'Production Studio',
  email: 'hello@productionstudio.com',
  phone: '+1 (555) 123-4567',
  address: 'Los Angeles, California',
  tagline: 'Crafting Visual Stories',
}
